# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

import base64

from odoo import fields, models


class L10nSiReportLog(models.Model):
    """History of generated regulatory reports (AJPES, REK-1, M4)."""
    _name = 'l10n_si.report.log'
    _description = 'Slovenian Regulatory Report Log'
    _order = 'create_date DESC'
    _rec_name = 'report_type'

    report_type = fields.Selection(
        selection=[('ajpes_srs', 'AJPES SRS'),
                   ('rek1', 'REK-1'),
                   ('m4', 'M4')],
        string='Report Type',
        required=True,
    )
    company_id = fields.Many2one('res.company', string='Company', required=True)
    date_from = fields.Date(string='Date From', required=True)
    date_to = fields.Date(string='Date To', required=True)
    version = fields.Integer(default=1, help='Re-generation increments the version.')
    xml_attachment_id = fields.Many2one(
        'ir.attachment', string='XML File', ondelete='restrict',
    )
    pdf_attachment_id = fields.Many2one(
        'ir.attachment', string='PDF File', ondelete='restrict',
    )
    state = fields.Selection(
        selection=[('draft', 'Draft'),
                   ('generated', 'Generated'),
                   ('submitted', 'Submitted to eDavki'),
                   ('accepted', 'Accepted'),
                   ('rejected', 'Rejected')],
        default='generated',
    )
    notes = fields.Text()
    generated_by = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user)

    def action_download_xml(self):
        self.ensure_one()
        if not self.xml_attachment_id:
            return False
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.xml_attachment_id.id}?download=true',
            'target': 'self',
        }

    def action_download_pdf(self):
        self.ensure_one()
        if not self.pdf_attachment_id:
            return False
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.pdf_attachment_id.id}?download=true',
            'target': 'self',
        }
