# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

import base64
import logging

from odoo import fields, models

_logger = logging.getLogger(__name__)


class L10nSiReportLog(models.Model):
    """History of generated regulatory reports (AJPES, REK-1, M4)."""
    _name = 'l10n_si.report.log'
    _description = 'Slovenian Regulatory Report Log'
    _order = 'create_date DESC'
    _rec_name = 'report_type'

    report_type = fields.Selection(
        selection=[('ajpes_srs', 'AJPES SRS'),
                   ('rek1', 'REK-1'),
                   ('m4', 'M4')],
        string='Report Type',
        required=True,
    )
    company_id = fields.Many2one('res.company', string='Company', required=True)
    date_from = fields.Date(string='Date From', required=True)
    date_to = fields.Date(string='Date To', required=True)
    version = fields.Integer(default=1, help='Re-generation increments the version.')
    xml_attachment_id = fields.Many2one(
        'ir.attachment', string='XML File', ondelete='restrict',
    )
    pdf_attachment_id = fields.Many2one(
        'ir.attachment', string='PDF File', ondelete='restrict',
    )
    state = fields.Selection(
        selection=[('draft', 'Draft'),
                   ('generated', 'Generated'),
                   ('submitted', 'Submitted to eDavki'),
                   ('accepted', 'Accepted'),
                   ('rejected', 'Rejected')],
        default='generated',
    )
    notes = fields.Text()
    generated_by = fields.Many2one('res.users', string='Generated By', default=lambda self: self.env.user)
    ai_summary = fields.Text(
        string='AI povzetek', copy=False,
        help='AI-generiran povzetek tega poročila za management',
    )

    def action_download_xml(self):
        self.ensure_one()
        if not self.xml_attachment_id:
            return False
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.xml_attachment_id.id}?download=true',
            'target': 'self',
        }

    def action_download_pdf(self):
        self.ensure_one()
        if not self.pdf_attachment_id:
            return False
        return {
            'type': 'ir.actions.act_url',
            'url': f'/web/content/{self.pdf_attachment_id.id}?download=true',
            'target': 'self',
        }

    def action_generate_ai_summary(self):
        """AI povzetek poročila za management.

        Uporablja AI Core za generiranje berljivega povzetka
        regulativnega poročila (REK-1, M4) iz XML vsebine.
        """
        AiCore = self.env.get('l10n_si.ai.core.route')
        if not AiCore:
            _logger.info('Reports AI: AI Core not installed — skipping')
            return True

        for report in self:
            # Pridobi XML vsebino
            xml_content = ''
            if report.xml_attachment_id:
                xml_data = base64.b64decode(report.xml_attachment_id.datas)
                xml_content = xml_data.decode('utf-8', errors='ignore')[:4000]

            prompt = (
                f"Ustvari kratek povzetek tega regulativnega poročila za "
                f"management:\n"
                f"Tip: {report.report_type}\n"
                f"Obdobje: {report.date_from} do {report.date_to}\n"
                f"Podjetje: {report.company_id.name}\n"
                f"Verzija: {report.version}\n"
                f"XML vsebina (skrajšana):\n{xml_content}\n\n"
                f"Napiši 3-5 stavkov v slovenščini: ključne številke, "
                f"stanje, morebitne nepravilnosti."
            )
            try:
                result = AiCore.generate(
                    messages=[{'role': 'user', 'content': prompt}],
                    task_type='reasoning',
                    system_prompt='Si finančni analitik v slovenskem podjetju. '
                                  'Povzemaš regulativna poročila za management '
                                  'v jasnem, razumljivem jeziku, v slovenščini.',
                    source_module='reports',
                )
                if result.get('success') and result.get('response'):
                    report.ai_summary = result['response']
                    _logger.info(
                        'Reports AI: summary for %s via %s/%s',
                        report.report_type, result.get('provider'),
                        result.get('model'),
                    )
                else:
                    _logger.warning(
                        'Reports AI: failed (%s)',
                        result.get('error', 'unknown'),
                    )
            except Exception as e:
                _logger.error('Reports AI: error: %s', e)
        return True
